services:
  face_recognition:
    build: 
      context: face_recognition
      network: host
    ports:
      - '8000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - face_recognition
    ports:
      - "8079:80"
