services:
  person:
    build: 
      context: person
      network: host
    ports:
      - '8000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - person
    ports:
      - "8000:80"
