GET http://127.0.0.1:5000/find/ HTTP/1.1
Content-Type: application/json

{
  "url": "https://firebasestorage.googleapis.com/v0/b/nuxt-blog-syds.appspot.com/o/reidvai1998%40gmail.com%2Ffound_shopno.jpg?alt=media"
}
###
POST http://localhost/find/ HTTP/1.1
Content-Type: application/json

{
  "url": "https://firebasestorage.googleapis.com/v0/b/nuxt-blog-syds.appspot.com/o/reidvai1998%40gmail.com%2Fshopno.jpg?alt=media",
  "face": "shopno"
}
###
PATCH http://localhost:5000/find/ HTTP/1.1
Content-Type: application/json

{
  "url": "https://firebasestorage.googleapis.com/v0/b/nuxt-blog-syds.appspot.com/o/reidvai1998%40gmail.com%2Fshopno.jpg?alt=media",
  "face": "631e1061b218dd4708b5edc2"
}
###
DELETE http://localhost:5000/find/ HTTP/1.1
Content-Type: application/json

{
  "face": "shopno"
}