services:
  rest_api:
    build: 
      context: rest_api
      network: host
    ports:
      - '8000'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rest_api
    ports:
      - "8079:80"
